pick: random

configs:
  win2021:
    os: windows
    isabelle: 2021-RC2
    scala: 213
    weight: 50
  linux2021:
    os: linux
    isabelle: 2021-RC2
    scala: 213
  macos2021:
    os: macos
    isabelle: 2021-RC2
    scala: 213
  win2021-212:
    os: windows
    isabelle: 2021-RC2
    scala: 212
    weight: 50
  linux2021-212:
    os: linux
    isabelle: 2021-RC2
    scala: 212
  macos2021-212:
    os: macos
    isabelle: 2021-RC2
    scala: 212

  win2020:
    os: windows
    isabelle: 2020
    scala: 213
    weight: 50
  linux2020:
    os: linux
    isabelle: 2020
    scala: 213
  macos2020:
    os: macos
    isabelle: 2020
    scala: 213
  win2020-212:
    os: windows
    isabelle: 2020
    scala: 212
    weight: 50
  linux2020-212:
    os: linux
    isabelle: 2020
    scala: 212
  macos2020-212:
    os: macos
    isabelle: 2020
    scala: 212


  # Isabelle 2019 does not run on Circle CI with the current config. It works when installing sbt via "choco install sbt", and then running "refreshenv & sbt test" in cmd (not bash)
  win2019:
    os: windows
    isabelle: 2019
    weight: 0
  linux2019:
    os: linux
    isabelle: 2019
    scala: 213
  macos2019:
    os: macos
    isabelle: 2019
    scala: 213

  # Isabelle 2019 does not run on Circle CI with the current config. It works when installing sbt via "choco install sbt", and then running "refreshenv & sbt test" in cmd (not bash)
  win2019-212:
    os: windows
    isabelle: 2019
    scala: 212
    weight: 0
  linux2019-212:
    os: linux
    isabelle: 2019
    scala: 212
  macos2019-212:
    os: macos
    isabelle: 2019
    scala: 212


defaults:
  machine_config: |
    if os=="windows": return "executor: { name: windows/default }"
    if os=="linux": return "machine: {image: ubuntu-2004:202010-01}"
    if os=="macos": return "macos: {xcode: 11.6.0}"
  isabellehome: |
    if os=="macos": return f"~/install/Isabelle{isabelle}.app/Isabelle"
    return f"~/install/Isabelle{isabelle}"
  sha1sum: |
    if os=="macos": return "shasum"
    return "sha1sum"
