version: 2.1

orbs:
  windows: circleci/windows@2.4.0

workflows:
  version: 2
  @{name}:
    jobs:
      - test:
          filters:
            branches:
              only:
                - circleci-project-setup

jobs:
  test:

    executor:
      name: windows/default # executor type

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache Isabelle
      - restore_cache:
          keys:
            - v2-isabelle-@{isabelle}
      - run:
          shell: bash
          command: |
            if ! [ -e "$HOME/install/Isabelle@{isabelle}" ]; then
              mkdir -p ~/install
              curl "https://isabelle.in.tum.de/website-Isabelle@{isabelle}/dist/Isabelle@{isabelle}.exe" -o /tmp/isabelle.exe
              7z x -y -o"$HOME/install" /tmp/isabelle.exe
            fi
      - save_cache:
          paths:
            - ~/install/Isabelle@{isabelle}
          key: v2-isabelle-@{isabelle}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}-{{ checksum "publish.sbt" }}
            - v2-dependencies-
            - dependencies-{{ checksum "build.sbt" }}-{{ checksum "publish.sbt" }}
            - dependencies-
      - run:
          shell: bash
          command: |
            mkdir -p ~/install
            if ! sha1sum -c ~/dependencies-sha1sum; then
              curl -Ls https://git.io/sbt > ~/install/sbt
              chmod +x ~/install/sbt
              ~/install/sbt update </dev/null
            fi
            sha1sum build.sbt publish.sbt > ~/dependencies-sha1sum
      - save_cache:
          paths:
            - ~/install/sbt
            - ~/.m2
            - ~/.sbt
            - ~/.ivy2
            - $LOCALAPPDATA\Coursier\Cache
            - ~/dependencies-sha1sum
          key: v2-dependencies-{{ checksum "build.sbt" }}-{{ checksum "publish.sbt" }}

      - run:
          shell: bash
          command: |
            # Isabelle process calls rebaseall and then fails, unless we deactivate it
            > ~/install/Isabelle@{isabelle}/contrib/cygwin/isabelle/rebaseall

            cygpath -w ~/install/Isabelle@{isabelle} > .isabelle-home
            #export PATH=~/bin:"$PATH"
            ~/install/sbt "testOnly -- -u scalatest-reports" </dev/null

      - store_test_results:
          path: scalatest-reports
