name: scala-isabelle
on: [push]
jobs:
    test:
      strategy:
        matrix:
          isabelle: [2019, 2020, 2021, 2021-1-RC3]
          os: [linux, windows, macos]
      runs-on: [self-hosted, "${{matrix.os}}"]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          
        - name: Running tests (Linux)
          if: matrix.os == 'linux'
          run: |
            export SCALA_ISABELLE_NO_CLEANUP=true
            echo /opt/Isabelle${{matrix.isabelle}} >.isabelle-home
            sbt '+ testOnly -- -h target/test-reports-html'

        - name: Running tests (Windows)
          if: matrix.os == 'windows'
          run: |
            $Env:SCALA_ISABELLE_NO_CLEANUP = "true"
            Set-Content -Path .isabelle-home -Value 'c:\Isabelle${{matrix.isabelle}}'
            sbt '+ testOnly -- -h target/test-reports-html'

        - name: Running tests (MacOS)
          if: matrix.os == 'macos'
          run: |
            export SCALA_ISABELLE_NO_CLEANUP=true
            case "${{matrix.isabelle}}" in
              2019|2020) echo ~/Isabelle${{matrix.isabelle}}.app/Isabelle >.isabelle-home;;
              *) echo ~/Isabelle${{matrix.isabelle}}.app >.isabelle-home;;
            esac
            sbt '+ testOnly -- -h target/test-reports-html'

        - name: Upload test results
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: test-reports-html-${{matrix.isabelle}}-${{matrix.os}}
            path: target/test-reports-html

    publish-snapshot:
      runs-on: [self-hosted, linux]
      needs: test
      if: github.ref == 'refs/heads/master'
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Publish snapshot
          run: sbt "+ publishSigned"
